stages:
  - test
  - build

run_mayday_test:
  image: gcr.io/mist-ops/fullstack:latest
  stage: test
  only:
    - triggers
  before_script:
    # hack to keep logs in subdir of build dir, required for artifacts to work
    - mkdir -p var/log
    - cp -a /var/log/* var/log/
    - rm -rf /var/log
    - ln -s $CI_PROJECT_DIR/var/log /var/log
    # end logs hack
    - echo "$GITLAB_ID_RSA" > /gitlab_id_rsa
    - export MAYDAY=1
    - export DISPLAY=:1.0
    - Xvfb :1 -screen 0 1024x768x24 > /dev/null 2>&1 &
    - cd ..
    - rm -rf tests
    - mkdir tests
    - cp -r -t tests mist.tests/*
    - cp /chromedriver tests/gitlab/chromedriver
    - chmod 744 tests/gitlab/chromedriver
    - export "PATH=$(pwd)/tests/gitlab:$PATH"
    - /core.env/bin/pip install -e tests
  script:
    - >
        /core.env/bin/ipython tests/prepare_env.py --
        --screenshot-path=/builds/mistio/mist.tests/var/log/error -k
        --tags=alert,graph,ssh,celery,google_sso_signin,github_sso_signin
        tests/legacy_gui/core/mayday/features
  tags:
     - mayday
  artifacts:
    paths:
      - var/log/*-std*
      - var/log/js_console.log
      - var/log/rabbitmq/*
      - var/log/supervisord.log
      - var/log/mongodb.log.*
      - var/log/mongodb.log.*
      - test.mp4
    expire_in: 7 days
    when: on_failure
