stages:
  - test
  - build

run_mayday_test:
  image: gcr.io/mist-ops/fullstack:latest
  stage: test
  only:
    - triggers
    - master
  before_script:
    - pwd
    - ls
    - export DISPLAY=:1.0
    - Xvfb :1 -screen 0 1024x768x24 > /dev/null 2>&1 &
    - cp /chromedriver /usr/local/bin/
    - chmod 744 /usr/local/bin/chromedriver
    - /core.env/bin/pip install -e $CI_PROJECT_DIR
  script:
    - >
        /core.env/bin/ipython prepare_env.py --
        --screenshot-path=$CI_PROJECT_DIR/var/log/error -k
        --webdriver-log=$CI_PROJECT_DIR/var/log/chromedriver.log
        --webdriver-path=/usr/local/bin/chromedriver
        --js-console-log=$CI_PROJECT_DIR/var/log/js_console.log
        -D BEHAVE_DEBUG_ON_ERROR
        -k --tags=alert,graph,ssh,celery,google_sso_signin,github_sso_signin
        $CI_PROJECT_DIR/misttests/legacy_gui/core/mayday/features
  artifacts:
    paths:
      - var/log/chromedriver.log
      - var/log/js_console.log
      - var/log/error.*
      - test.mp4
    expire_in: 7 days
    when: always
