stages:
  - build

#################### BUILD STAGE ####################
.docker_build_template: &docker_build_template
  stage: build
  before_script:
    - docker login --username "$DOCKER_USERNAME" -u _json_key -p "$KEYFILE_JSON" https://gcr.io
    - docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD"
  tags:
    - builder
  dependencies: []

build_landing_image:
  <<: *docker_build_template
  script:
    - docker build --rm -t gcr.io/mist-ops/landing:$CI_COMMIT_SHA .
    - docker tag gcr.io/mist-ops/landing:$CI_COMMIT_SHA gcr.io/mist-ops/landing:$CI_COMMIT_REF_SLUG
    - docker tag gcr.io/mist-ops/landing:$CI_COMMIT_SHA mist/landing:$CI_COMMIT_SHA
    - docker tag gcr.io/mist-ops/landing:$CI_COMMIT_REF_SLUG mist/landing:$CI_COMMIT_REF_SLUG
    - docker push gcr.io/mist-ops/landing:$CI_COMMIT_SHA
    - docker push gcr.io/mist-ops/landing:$CI_COMMIT_REF_SLUG
    - docker push mist/landing:$CI_COMMIT_SHA
    - docker push mist/landing:$CI_COMMIT_REF_SLUG
