stages:
    - test
    - build

run_mayday_test:
    image: gcr.io/mist-ops/fulltest2:2.10
    stage: test
    only:
        - triggers
    before_script:
        # export all the necessary env variables
        - export PATH=/builds/mistio/tests/parts/chromedriver/:$PATH
        # initialize directories
        - mkdir -p /builds/mistio/mist.tests/parts/chromedriver
        - mkdir -p /builds/mistio/mist.tests/var/mail
        # cp chromedriver and script
        - cp /tests2/chromedriver /builds/mistio/mist.tests/parts/chromedriver/chromedriver
        # fix permissions for copied files
        - chmod 744 /builds/mistio/mist.tests/parts/chromedriver/chromedriver
        - export DISPLAY=:1.0
        - Xvfb :1 -screen 0 1024x768x24 > /dev/null 2>&1 &
    script:
        - mv /builds/mistio/mist.tests /builds/mistio/tmp
        - mkdir /builds/mistio/mist.tests
        - mkdir /builds/mistio/mist.tests/tests
        - cp -r /builds/mistio/tmp /builds/mistio/mist.tests/tests
        - cp -r /builds/mistio/tmp /builds/mistio/mist.tests 
#        - /core.env/bin/ipython /mist.core/tests/prepare_env.py -- --register_user_before_feature false -k --tags=alert,graph,ssh,celery,google_sso_signin,github_sso_signin mist.tests/gui/core/mayday/features
        - /core.env/bin/ipython /builds/mistio/mist.tests/prepare_env.py -- -k --tags=google_sso_signin /tests/gui/core/mayday/features


raise_mayday:
    image: gcr.io/mist-ops/fulltest2:2.10
    stage: build
    when: on_failure
    script:
        - /core.env/bin/ipython check_last_build.py
