stages:
    - test
    - build

run_mayday_test:
    image: gcr.io/mist-ops/fulltest2:2.10
    stage: test
    only:
        - triggers
    before_script:
        - echo "$GITLAB_ID_RSA" > /gitlab_id_rsa
        - export PATH=/builds/mistio/tests/gitlab:$PATH
        - export MIST_TEST_LOG_DIR="mayday/$CI_BUILD_ID"
        - export DISPLAY=:1.0
        - Xvfb :1 -screen 0 1024x768x24 > /dev/null 2>&1 &
        - rm -rf /builds/mistio/tests
        - mv /builds/mistio/mist.tests /builds/mistio/tests
        - chmod 744 /builds/mistio/tests/gitlab/chromedriver
        - chmod 744 /builds/mistio/tests/gitlab/run_test_or_commit.sh
    script:
        - cd /builds/mistio
#        - ./tests/gitlab/run_test_or_commit.sh /core.env/bin/ipython tests/prepare_env.py -- --screenshot-path=/var/log/error -k --tags=alert,graph,ssh,celery,google_sso_signin,github_sso_signin tests/gui/core/mayday/features
        - ./tests/gitlab/run_test_or_commit.sh /core.env/bin/ipython tests/prepare_env.py -- --screenshot-path=/var/log/error -k --tags=github_sso_signin tests/gui/core/mayday/features
        - cd ..
        - mv tests mist.tests
    tags:
        - mayday


raise_mayday:
    image: gcr.io/mist-ops/fulltest2:2.10
    stage: build
    when: on_failure
    script:
        - /core.env/bin/ipython check_last_build.py
    tags:
        - mayday
