stages:
  - test

.mayday_tests_template: &mayday_tests_template
  stage: test
  image: gcr.io/mist-ops/tests_base
  tags:
    - shm
  only:
    - triggers
  before_script:
    - echo $MAYDAY_SETTINGS | base64 -d > test_settings.py
    - export DISPLAY=:1.0
    - pip install -e .
  artifacts:
    paths:
      - js_console.log
      - error*
      - test.mp4
    expire_in: 7 days
    when: always


alert:
  <<: *mayday_tests_template
  script:
    - python prepare_env.py -k --tags=alert misttests/gui/core/mayday/features

celery:
  <<: *mayday_tests_template
  script:
    - python prepare_env.py -k --tags=celery misttests/gui/core/mayday/features

graph:
  <<: *mayday_tests_template
  script:
    - python prepare_env.py -k --tags=graph misttests/gui/core/mayday/features

sso_logins:
  <<: *mayday_tests_template
  script:
    - python prepare_env.py -k --tags=sso_logins misttests/gui/core/mayday/features

ssh:
  <<: *mayday_tests_template
  script:
    - python prepare_env.py -k --tags=ssh misttests/gui/core/mayday/features
