stages:
    - test
    - build

run_mayday_test:
    image: gcr.io/mist-ops/fulltest2:2.10
    stage: test
    only:
        - triggers
    before_script:
        # export all the necessary env variables
        - export PATH=/builds/mistio/mist.tests/gitlab/chromedriver/:$PATH
        - export DISPLAY=:1.0
        - Xvfb :1 -screen 0 1024x768x24 > /dev/null 2>&1 &
        # symlink tests to simulate the paths used for mist.core
        - rm -rf /builds/mistio/mist.tests/tests
        - ln -s /builds/mistio/mist.tests /builds/mistio/mist.tests/tests
    script:
#        - /core.env/bin/ipython /mist.core/tests/prepare_env.py -- --register_user_before_feature false -k --tags=alert,graph,ssh,celery,google_sso_signin,github_sso_signin mist.tests/gui/core/mayday/features
        - /core.env/bin/ipython /builds/mistio/mist.tests/prepare_env.py -- -k --tags=google_sso_signin /builds/mistio/mist.tests/gui/core/mayday/features
        - tail /builds/mistio/mist.tests/var/log/chromedriver.log


raise_mayday:
    image: gcr.io/mist-ops/fulltest2:2.10
    stage: build
    when: on_failure
    script:
        - /core.env/bin/ipython check_last_build.py
