{{- if .Values.userAdminCreation.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
data:
  mail: {{ .Values.userAdminCreation.mail | b64enc | quote }}
  {{- if .Values.userAdminCreation.password }}
  password: {{ .Values.userAdminCreation.password | b64enc | quote }}
  {{- else }}
  password: {{ randAlphaNum 20 | b64enc | quote }}
  {{- end }}
  {{- if .Values.userAdminCreation.createApiToken }}
  apiToken: {{ randAlphaNum 64 | lower | b64enc | quote }}
  {{- else }}
  apiToken: ""
  {{- end }}
metadata:
  name: {{ .Release.Name }}-user-creation-secret
  labels:
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
{{- end }}
