{{- if .Values.vault.deploy }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace .Values.vault.mistSecretName) }}

{{- $roleId := uuidv4 | b64enc | quote }}
{{- $secretId := uuidv4 | b64enc | quote }}

{{- if $secret }}
{{- $roleId = index $secret.data "roleId" }}
{{- $secretId = index $secret.data "secretId" }}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.vault.mistSecretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
  roleId: {{ $roleId }}
  secretId: {{ $secretId }}
{{- end }}