{{ if .Values.vault.deploy }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
{{- with (index .Values.vault.server.volumes 2) }}
  name: {{ .persistentVolumeClaim.claimName }}
{{- end }}
  labels:
    app: vault
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{{- end }}
