{{ if .Values.vault.deploy }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.vault.mistRootCredentialsPVC }}
  labels:
    app: vault
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
{{- end }}
