info:
  title: MistIO API
  version: 2.0.0
openapi: 3.0.0
servers:
  - url: http://localhost
produces:
- application/json
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
security:
  - ApiKeyAuth: []
paths:
