info:
  title: MistIO API
  version: 1.0.0
openapi: 3.0.0
servers:
  - url: http://172.17.0.1
produces:
- application/json
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
security:
  - ApiKeyAuth: []
paths:
