name: CI

on:
  push:
    branches:
      - main
  # pull_request:
  workflow_dispatch:

jobs:
  build-portal:
    name: Build portal Image
    runs-on: ubuntu-latest
    env:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${GHCR_TOKEN}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build portal image
        run: |
          docker build --rm -t "ghcr.io/${GITHUB_REPOSITORY_OWNER##*/}/portal:${GITHUB_SHA}" .
          docker push "ghcr.io/${GITHUB_REPOSITORY_OWNER##*/}/portal:${GITHUB_SHA}"
